# This is a basic workflow to help you get started with Actions

name: SGSI_Build

on:
  watch:
    types: [started]
    
env:              
  ROM_URL: https://dl.google.com/developers/android/sc/images/ota/redfin-ota-spp2.210219.008-3d61e529.zip
  ZIP_NAME: test.zip
  OS_TYPE: Pixel
  BUILD_TYPE: 'ab'
  REPACK_NAME: test_action.zip
  VERSION: 12
  upload_WeTransfer: 'true'
  upload_action-gh-release: 'false'
  SETUP: 'true'
  
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
       - name: Checkout
         uses: actions/checkout@main
       
           
       - name: Setting up the SPICES
         run: |
            sudo apt-get install -y git openjdk-8-jdk wget git zip unzip curl
       - name: Cloning...
         run: |
             git clone https://github.com/xiaoxindada/SGSI-build-tool.git -b 12 $GITHUB_WORKSPACE/SGSI-build-tool
           
       - name: Download zip...
         run: |
            cd $GITHUB_WORKSPACE/SGSI-build-tool
            mkdir ./tmp
            cd ./tmp
            sudo wget $ROM_URL -O $ZIP_NAME && ls
            
       - name: Setup Tool Utils...
         if: env.SETUP == 'true'
         run: |
            sudo bash $GITHUB_WORKSPACE/SGSI-build-tool/setup.sh
       - name: Building AB DEVICES SGSI...
         if: env.BUILD_TYPE == 'AB' || env.BUILD_TYPE == 'ab'
         run: |
            sudo bash $GITHUB_WORKSPACE/SGSI-build-tool/make.sh --AB $OS_TYPE $ZIP_NAME --fix-bug
       - name: Building A-only DEVICES SGSI...
         if: env.BUILD_TYPE == 'a-only'
         run: |
            sudo bash $GITHUB_WORKSPACE/SGSI-build-tool/make.sh --a-only $OS_TYPE $ZIP_NAME --fix-bug            
       - name: Repack output file ...
         run: |            
             cd $GITHUB_WORKSPACE/SGSI-build-tool
             pwd
             zip -r $REPACK_NAME ./SGSI/*
             ls "$REPACK_NAME"
       - name: Upload SGSI to WeTransfer...
         if: env.upload_WeTransfer == 'true' 
         run: |
           cd $GITHUB_WORKSPACE/SGSI-build-tool
           pwd
           ls "$REPACK_NAME"
           curl -sL https://git.io/file-transfer | sh
           ./transfer wet ./$REPACK_NAME
       - name: Upload SGSI to action-gh-release...
         if: env.upload_action-gh-release == 'true'
         uses: softprops/action-gh-release@v1
         with:
           files: ${{ github.workspace }}/SGSI-build-tool/${{ env.REPACK_NAME }}
           name: xiaoxinSGSI-${{ env.OS_TYPE }}-${{ env.BUILD_TYPE }}-Android${{ env.VERSION }}-unpack
           tag_name: 12
           #body: Use actions auto bulid
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       
